# Generated by Django 3.2.19 on 2023-07-04 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_filter',
            field=models.CharField(choices=[('novice', 'Novice'), ('intermediate', 'Intermediate'), ('professional', 'Professional')], default='normal', max_length=32),
        ),
    ]
