# Generated by Django 3.2.19 on 2023-07-04 22:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_image_filter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image_filter',
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('novice', 'Novice'), ('intermediate', 'Intermediate'), ('professional', 'Professional')], default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='../default_profile_vvucyn', upload_to='images/'),
        ),
    ]
