# Generated by Django 3.2.19 on 2023-07-05 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_image_filter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image_filter',
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('novice', 'Novice'), ('intermediate', 'Intermediate'), ('professional', 'Professional')], default='normal', max_length=50),
        ),
    ]
